# Change these first
owner: wwmwabini # Your GitHub organization or username, where this repository lives
repo: statuspages # The name of this repository

sites:
  - name: Truehost.co.ke
    url: https://truehost.co.ke
    expectedStatusCodes:
      - 200
      - 201
      - 403
  - name: Truehost.com.ng
    url: https://truehost.com.ng
    expectedStatusCodes:
      - 200
      - 201
      - 403
  - name: Truehost.co.za
    url: https://truehost.co.za
    expectedStatusCodes:
      - 200
      - 201
      - 403
  - name: Truehost.cloud
    url: https://truehost.cloud
    expectedStatusCodes:
      - 200
      - 201
      - 403
  - name: Truehost.com
    url: https://truehost.com
    expectedStatusCodes:
      - 200
      - 201
      - 403
  - name: Truehost.co.in
    url: https://truehost.co.in
    expectedStatusCodes:
      - 200
      - 201
      - 403
  - name: Truehost.london
    url: https://truehost.london
    expectedStatusCodes:
      - 200
      - 201
      - 403
  - name: Truehost.ca
    url: https://truehost.ca
    expectedStatusCodes:
      - 200
      - 201
      - 403
    #Support Channels
  - name: Zola
    url: https://chat.olitt.net
  - name: Tickets
    url: https://tickets.olitt.com/en
  - name: Voice Call
    url: https://truehost.elastix.com/webclient/#/login
    #Shared Hosting Servers
  - name: frt106
    url: https://frt106.truehost.cloud
  - name: bhs105
    url: https://bhs105.truehost.cloud
  - name: gra106
    url: https://gra106.truehost.cloud
  - name: gra107
    url: https://gra107.truehost.cloud
  - name: gra108
    url: https://gra108.truehost.cloud
  - name: gra109
    url: https://gra109.truehost.cloud
  - name: gra110
    url: https://gra110.truehost.cloud
  - name: lim106
    url: https://lim106.truehost.cloud
  - name: lim107
    url: https://lim107.truehost.cloud
  - name: lim108
    url: https://lim108.truehost.cloud
  - name: lim109
    url: https://lim109.truehost.cloud
  - name: lim110
    url: https://lim110.truehost.cloud
  - name: lim112
    url: https://lim112.truehost.cloud
  - name: lon105
    url: https://lon105.truehost.cloud
  - name: lon106
    url: https://lon106.truehost.cloud
  - name: lon108
    url: https://lon108.truehost.cloud
  - name: lon109
    url: https://lon109.truehost.cloud
  - name: nyc101
    url: https://nyc101.truehost.cloud
  - name: nyc102
    url: https://nyc102.truehost.cloud
  - name: pld107
    url: https://pld107.truehost.cloud
  - name: pld108
    url: https://pld108.truehost.cloud
  - name: pld109
    url: https://pld109.truehost.cloud
  - name: rbx106
    url: https://rbx106.truehost.cloud
  - name: rbx107
    url: https://rbx107.truehost.cloud
  - name: rbx108
    url: https://rbx108.truehost.cloud
  - name: rbx109
    url: https://rbx109.truehost.cloud
  - name: rbx110
    url: https://rbx110.truehost.cloud
  - name: rbx111
    url: https://rbx111.truehost.cloud
  - name: sbg106
    url: https://sbg106.truehost.cloud
  - name: sbg108
    url: https://sbg108.truehost.cloud
  - name: tor101
    url: https://tor101.truehost.cloud
  - name: tor102
    url: https://tor102.truehost.cloud
  - name: rbx112
    url: https://rbx112.truehost.cloud
    #Truehost Email (Cloudoon Mail)
  - name: sm1::SMTP::STARTTLS
    check: "tcp-ping"
    url: 51.83.3.151
    port: 587
  - name: sm1::SMTP::SSL
    check: "tcp-ping"
    url: 51.83.3.151
    port: 465
  - name: sm1::IMAP
    check: "tcp-ping"
    url: 51.83.3.151
    port: 143
  - name: sm1::POP3
    check: "tcp-ping"
    url: 51.83.3.151
    port: 110
  - name: lon103::SMTP::STARTTLS
    check: "tcp-ping"
    url: 54.38.215.133
    port: 587
  - name: lon103::SMTP::SSL
    check: "tcp-ping"
    url: 54.38.215.133
    port: 465
  - name: lon103::IMAP
    check: "tcp-ping"
    url: 54.38.215.133
    port: 143
  - name: lon103::POP3
    check: "tcp-ping"
    url: 54.38.215.133
    port: 110
   #Web Applications
  - name: Jisort Portal
    url: https://my.jisort.com
  - name: Olitt Shops/Sites
    url: https://www.olitt.com
  - name: Cloudpap VMs
    url: https://console.cloudpap.com/
    
  #Website Front
  - name: Jisort WP
    url: https://jisort.com
  - name: Cloudpap WP
    url: https://cloudpap.com
    
  
  #ERP
  - name: Odoo
    url: https://dash.cloudoon.com
    
  #VPS
  - name: master.sbg2
    check: "tcp-ping"
    url: master.sbg2.truehost.cloud
    port: 4085
    
  #Registries
  - name: Namesilo
    url: https://namesilo.com/
    expectedStatusCodes:
      - 200
      - 201
      - 403
  - name: Connectreseller
    url: https://global.connectreseller.com
  - name: Kenic
    url: https://registry.kenic.or.ke
  - name: NiRA
    url: https://registry.nic.net.ng
  - name: CozaEPP
    url: https://portal.registry.net.za/login.php
   
    

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.truehost.com
  theme: light
  #baseUrl: /statuspages
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Truehost Monitoring** powered by **Upptime**."
  introMessage: This website shows the status of various Truehost Cloud services. 
  navbar:
    - title: Status
      href: /statuspages
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

assignees:
  - wwmwabini

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
